.github/workflows/release.yaml
.github/workflows/versions.txt

HTTPS support with Mbed TLS

---

.github/workflows/get-version.sh

Based on feedback from
https://github.com/joeyparrish/static-ffmpeg-binaries/pull/3#discussion_r716918304

docs: Add comments to get-version.sh

---

.github/workflows/build.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml

Split the build instructions into a reusable workflow, then call it
from both release and test workflows.
Closes #11

ci: Test static-ffmpeg-binaries PRs

---

.github/workflows/build-matrix.json
.github/workflows/build.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml

Before this, forks would attempt to run a self-hosted job that would likely never be able to start.  Now, this is disabled by default.
A fork can enable self-hosted jobs by hosting an appropriate runner and setting a repo secret called ENABLE_SELF_HOSTED.  The official repo will have this setting enabled.
This also allows debugging via tmate to be enabled and disabled as needed via the repo secret ENABLE_DEBUG, without a commit to the repo.

ci: Enable debugging and self-hosted jobs through repo secrets

---

.github/workflows/build.yaml

This fixes several (but not quite all) issues with building in GitHub Actions environments:
- macOS: Unlink additional conflicting libraries now installed by default through homebrew
- Windows: Install msys tools that _used_ to be installed by default, but now need msys versions to be explicitly installed
- Windows: Drop gcc from update list to avoid hanging while installing packages (not sure why this works)
- Linux: Fix location of libaom pkg-config file
- All: Upload artifacts before checking them, so that the binaries can be debugged if they fail a later check
Remaining issues:
- FFmpeg build can't find libaom on Windows... but I plan to remove aom shortly.

fix: Fix builds in latest GitHub environments

---

.github/workflows/build.yaml
.github/workflows/versions.txt

We can get x265 from git now, instead of the aptly-named mercurial.
x264 still has no tags, branches, or release numbers, but x265 does. This now uses a specific tag of x265, and uses a specific revision of x264 (the most recent SHA1 as of today).
This should make the build more stable.

fix: Update x264 and x265, use specific revisions

---

.github/workflows/build.yaml

> The `set-output` command is deprecated and will be disabled soon.
> Please upgrade to using Environment Files. For more information see:
> https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: Fix warning about the deprecation of set-output

---

.github/workflows/build.yaml

When we process the flag through JS, then print it, it becomes "true" or "false".  But we compared it to "".
The processing turns out to be necessary, since you can't refer to secrets directly when build.yaml is called from another workflow like test.yaml.  So we just fix the condition to check for "true".

ci: Fix ENABLE_DEBUG flag always interpreted as true

---

.github/workflows/build.yaml

GitHub's VMs have a broken version of pkg-config installed in C:\Strawberry, as part of a Perl installation.  We need to explicitly install the msys version to allow ffmpeg to correctly detect all of its dependencies on Windows.
Issue #13

fix: Fix Windows pkg-config issues

---

build-scripts/08-ffmpeg.sh

This note mentioned trying again with newer FFmpeg versions.  Now we have.

chore: Update note on macOS flags

---

build-scripts/08-ffmpeg.sh

This helps debug configuration failures.

ci: Dump ffmpeg config.log when configure fails

---

build-scripts/08-ffmpeg.sh

This seems to require dynamic libraries, and the static build with nvenc does not seem to be portable.  Linux users who want hardware acceleration with nvenc may have to use another FFmpeg binary, such as one built from source or the one provided by their Linux distro.  With the addition of SVT-AV1 for fast software encoding, this should not be a huge deal.

feat: Disable nvenc on Linux

---

.github/workflows/build.yaml

This makes it easier to test changes on a fork.

ci: Allow manual triggering of the build

---

build-scripts/09-check-static.sh

This should help in debugging non-portable binaries.

ci: Log dynamic library dependencies

---

.github/workflows/build.yaml
build-scripts/08-ffmpeg.sh

In GitHub's VMs, there are already GCC toolchains installed with Strawberry Perl, Git, and one more through Chocolatey.  None of these build clean executables that only depend on standard DLLs.  Installing an explicitly mingw toolchain gives us a working toolchain that is higher in the path than these others.
Getting this far also exposed an error caused by an updated mingw binutils combined with some sign errors in ffmpeg's x86 assembly.  So this adds a patch from a newer version of ffmpeg to resolve that build failure.
Issue #13

fix: Install explicit toolchain for Windows

---

build-scripts/02-svt-av1.sh
build-scripts/06-opus.sh
build-scripts/07-mbedtls.sh

CMake-based deps were being installed to C:/Program Files by default on Windows instead of /usr/local.
Issue #13

fix: Fix Windows install paths of all deps

---

.github/workflows/test.yaml

This allows configuration variables to be access by pull request tests.  This is necessary to fix our broken use of secrets in a follow-up PR.

ci: Change test trigger

---

build-matrix.json
build-scripts/01-libvpx.sh
build-scripts/07-mbedtls.sh

This uses a self-hosted runner in our lab to do macOS arm64 builds.

feat: Add macOS arm64 builds

---

build-matrix.json

Replaces self-hosted Actions runner with GitHub-hosted VM.
Closes #40

feat: Add macOS arm64 builds via GitHub Actions VM

---

build-scripts/00-packages.sh

Errors from "brew unlink" like "Error: No such keg: /opt/homebrew/Cellar/aom" are not important for us, since we are proactively removing homebrew packages that could potentially interfere with static linking.  But GitHub Actions sees "Error: " in the log and promotes this line to the summary for the job.
Since nothing in "brew unlink" output matters, silence that command completely.

fix: Silence nonsense macOS errors in GitHub Actions

---

.github/workflows/build.yaml
README.md
build-matrix.json
build-scripts/00-packages.sh
is-alpine.sh

This uses an Alpine Linux container to build truly static Linux binaries that do not depend on glibc at runtime.
Alpine uses musl instead of glibc, which enables this fully static build.  With musl compiler wrappers in Ubuntu, you still end up importing glibc references through libstdc++.  And since x265 uses C++, we can't eliminate these in Ubuntu without dropping HEVC support. Using Alpine, with its musl-native environment, allows us to avoid glibc and build fully static Linux binaries.
Closes #28

feat: Build with Alpine for static Linux binaries

---

.gitignore
README.md
build-scripts/00-packages.sh
build.sh

When making changes to this process, it really helps to have a simple container environment to test changes.  This adds a script for a fully-automated build with standard Ubuntu containers to make it easier to check build script changes before deploying them to the repo.

feat: Build locally in Docker to streamline testing

---

.github/workflows/test.yaml

The concurrency group expression for the test workflow would work for pull_request triggers, but not pull_request_target triggers.  This is because github.ref for pull_request is something like refs/pull/<pr_number>/merge, whereas for pull_request_target triggers it only references the target branch like refs/heads/main.
Instead we use github.event.number, which is the PR number, and fall back to github.run_id, which should be unique for manually-triggered runs of the workflow.

ci: Fix concurrent test runs

---

.github/workflows/build.yaml
build-matrix.json
build-scripts/00-packages.sh
build-scripts/90-ffmpeg.sh
build-scripts/99-check-static.sh
ffmpeg-nvenc-jammy.patch
versions.txt

Hardware acceleration for Linux is too wrapped up in dynamic libraries and drivers, so from now on, builds for Linux that support hardware encoding will be dynamic and will only run on Ubuntu.  For use in every other Linux distribution, fully static builds will be done with musl in Alpine Linux.
This also updates to the latest release, FFmpeg n7.1.

feat: Separate Linux static from hardware encoding

---

.github/workflows/release.yaml

This was mistaken ever since we moved the file, but we haven't made any releases since then.  The effect of this bug would be to have the "versions" section of the release notes be empty.

ci: Correct versions file path in release workflow

---

.github/workflows/build.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml

This was found by auditing workflows based on research published here:
https://github.com/joeyparrish/workflow-cheat-sheet
The research was prompted by a workflow bug in Shaka Streamer

ci: Fix workflow events

---

.github/workflows/build.yaml

The older version is deprecated and will stop working next month.

ci: Update upload-artifact

---

build-scripts/90-ffmpeg.sh

Enabling position independent code (PIC) resolves a crash in macOS arm64 builds.  The idea to try this came from a relocation-related build failure on another machine, followed by me stubmling across a note that iOS requires PIC.
Closes #51

fix: Fix macOS arm64 crashes

---

.github/workflows/build.yaml
.github/workflows/release.yaml

See actions/checkout#485 and https://johnstawinski.com/2024/01/11/playing-with-fire-how-we-executed-a-critical-supply-chain-attack-on-pytorch/
In short, it is a terrible idea to persist even our default credentials after checkout. There's no call for that, so we will now set `persist-credentials: false` on all checkout actions.

ci: Do not persist credentials after checkout

---

build-matrix.json

These are no longer required since GitHub launched their own Linux/arm64 runners.
See https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/

ci: Stop using self-hosted Linux/arm64 runners

---

.github/workflows/build.yaml
.github/workflows/settings.yaml
.github/workflows/test.yaml

With this change, GitHub will start to enforce "require approval" settings for the repo, which `pull_request_target` allows PR authors to get around.
To stop using `pull_request_target`, we also have to stop using `vars`, which are not available on `pull_request` triggers.  Instead, we use the "environments" trick used by Shaka Packager's workflows before `vars` was introduced to GitHub Actions.  This is a safer system.

ci: Switch pull_request_target to pull_request
